version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - DATABASE_URI=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=db
      - REPLICA_SET=rs0
    restart: always
  mongo:
    hostname: mongo
    image: mongo
    volumes:
      - "~/docker/mongo:/data/db"
    command: --replSet rs0
    restart: always